1주차 - 손성훈
AUSG/2022-system-design pull request #3
Opened 2022-09-05 02:40 UTC by kaonmir

## 변경사항 
``` plaintext
- [1주차]
|-- assets : 이미지
|-- 1주차-손성훈.md

- README
```

2022-09-05 11:28 UTC, 14km requested changes
디렉토리 구조를 변경했습니다 :)

확인 후 수정해주실 수 있나요?

2022-09-05 11:30 UTC, kshired commented
@14km 
이전 PR을 close하고, 변경해서 올린 PR입니다!

2022-09-06 06:37 UTC, kaonmir commented
변경했습니다!

2022-09-06 08:12 UTC, 14km approved these changes

2022-09-06 08:12 UTC, merged